name: Update plots

on:
  push:
    branches:
      - main

jobs:
  run-r:
    name: Run .Rmd and save generated .svgs
    # Update plots only if commit message contains keywords 'Add data' (not case-sensitive)
    if: "contains(github.event.head_commit.message, 'Add data')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install needed R packages
        run: |
          R -e "install.packages('knitr')"
      - name: Make README and *.svg plots
        run: |
          make README.md
      - name: Commit generated plots
        run: |
          git config --local user.name "Update Action"
          git config --local user.email "actions@github.com"
          git add *.svg
          git commit -m 'Update plots' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
